### ISSUE TITLE
Manual Test: Student should be able to create a team

### ISSUE THREAD

**Issue by sak007** [sak1997/expertiza#11]

**Comment by wizard-31** [comment]
While creating a team - "You no longer have a team!" is seen when user clicks on "Your Team" to create a team for an assignment.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/28624935/165131979-3ebba70e-2b2d-43b9-910f-aed180e5ae5d.png">

**Comment by wizard-31** [comment]
That error should come only when a user leaves a team

**Comment by wizard-31** [comment]
Works as expected. We're good to close this Issue. @sak007
