### ISSUE TITLE
Manual Test: Instructor should be able to create a team manually

### ISSUE THREAD

**Issue by sak007** [sak1997/expertiza#13]

**Comment by wizard-31** [comment]
Instructor is able to create a team - but when he creates he become part of the team. 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/28624935/165132260-995c72d5-59a7-4b1f-a141-0d6fd3dfbb89.png">

Instructor gets considered as a Student here.

**Comment by wizard-31** [comment]
Works the same in our beta and main expertiza beta. We're good to close the issue
