### ISSUE TITLE
Manual Test: Instructor should be able to create teams automatically

### ISSUE THREAD

**Issue by sak007** [sak1997/expertiza#14]

**Comment by sak1997** [comment]
Tested both on our beta branch and the main expertiza beta branch. Similar behaviour observed in both cases - automatic team creation seems to be working as expected:

Screenshot from our beta branch

![image](https://user-images.githubusercontent.com/28535703/165137451-7d2c88fb-3254-489b-b262-2d40032c7f3b.png)

**Comment by sak1997** [comment]
Good to close
