### ISSUE TITLE
Manual Test: Instructor should be able to import teams

### ISSUE THREAD

**Issue by sak007** [sak1997/expertiza#25]

**Comment by wizard-31** [comment]
This issue seems to throw an error in both our beta branch and expertiza's main beta branch. 
The changes made by our code has not affected this in any way. 

<img width="604" alt="image" src="https://user-images.githubusercontent.com/28624935/165137699-99298061-4e0e-47ac-a5ba-cd500ba4f687.png">

**Comment by wizard-31** [comment]
We're good to close this issue - @sak007
